name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
      # Specify runner +  build & upload the static files as an artifact
      runs-on: ubuntu-latest
      steps:
        - name: Build static files
          id: build
          run: npm run build

        - name: Upload static files as artifact
          id: deployment
          uses: actions/upload-pages-artifact@v4 # or specific "vX.X.X" version tag for this action
          with:
            path: dist/

  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - uses: actions/checkout@v5
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4

      - uses: withastro/action@v4
        with:
          deploy_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}